### ISSUE TITLE
Unexpected credentials error / EncryptedPasswd

### ISSUE THREAD

**Issue by ashleyevans** [mgansler/GPSOAuthPHP#1]
Hi

when using performMasterLogin() I receive a "unexpected credentials" error, seemingly due to it using Passwd instead of EncryptedPasswd. I can see you have a encryptedPasswd branch but it doesn't seem complete, any plans to complete the EncryptedPasswd functionality?

Thanks

**Comment by mgansler** [comment]
Hi, currently this project is more or less dead. It may be revived in September but until than I won't do any work on it. If you want to work on the `EncryptedPasswd` go ahead!

**Comment by ashleyevans** [comment]
fair enough, thanks for the response. If still needed I might look into it and submit a PR if I do get it working
